---
title: "Michele_Lotto_Exercises"
author: "Michele Lotto"
date: "2022-11-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
```

# Michele Lotto Exercises

4) 3.21
8) 5.22

## List 4 - Exercise 3.21
If A flips $n + 1$ and B flips $n$ fair coins, show that the
probability that A gets more heads than B is $\frac{1}{2}$.

Hint: Condition on which player has more heads after each
has flipped n coins. (There are three possibilities.)

### Solution



## List 8 - Exercise 5.22
Let U be a uniform $(0, 1)$ random variable, and let
$a < b$ be constants.

(a) Show that if $b > 0$, then $bU$ is uniformly distributed
on $(0, b)$, and if $b < 0$, then $bU$ is uniformly distributed on
$(b, 0)$.

(b) Show that $a + U$ is uniformly distributed on $(a, 1 + a)$.

(c) What function of $U$ is uniformly distributed on $(a, b)$?

(d) Show that $min(U, 1 - U)$ is a uniform $(0, 1/2)$ random
variable.

(e) Show that $max(U, 1 - U)$ is a uniform $(1/2, 1)$ random
variable.

### Solution

Let $U \sim U(0,1)$ with PDF:

$$
f_U(x)= 
\begin{cases}
1, & x \in [0,1] \\
0, & \text{otherwise}
\end{cases}
$$
and CDF:
$$
F_U(x)= 
\begin{cases}
0, & x<0 \\ 
x, & x \in [0,1] \\
1, & x >1
\end{cases}
$$

a.1 ) We have to prove that if $b>0$ then $Y=bU \sim U(0,b)$

First we calculate the interval extremes:

* if $U=0$ then $Y=0$

* if $U=1$ then $Y=b$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(bU \le y)=P(U \le \frac{y}{b})=F_U(\frac{y}{b})=\frac{y}{b}$

Given that $\frac{\partial F}{\partial y}=\frac{1}{b}$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
\frac{1}{b}, & y \in [0,b] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(0,b)$ by definition.

a.2 ) We have to prove that if $b<0$ then $Y=bU \sim U(b,0)$

First we calculate the interval extremes:

* if $U=0$ then $Y=0$

* if $U=1$ then $Y=b$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(bU \le y)=P(U \ge \frac{y}{b})=1-F_U(\frac{y}{b})=1-\frac{y}{b}$

Given that $\frac{\partial F}{\partial y}=\frac{-1}{b}$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
\frac{-1}{b}, & y \in [b,0] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(b,0)$ by definition.

b ) We have to prove that $Y=a+U \sim U(a,1+a)$

First we calculate the interval extremes:

* if $U=0$ then $Y=a$

* if $U=1$ then $Y=1+a$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(a+U \le y)=P(U \le y-a)=F_U(y-a)=y-a$

Given that $\frac{\partial F}{\partial y}=1$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
1, & y \in [a,1+a] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(a,1+a)$ by definition.

d ) We have to prove that $Y=min(U,1-U) \sim U(0,1/2)$

We distinguish two cases:

1) if $U \ge \frac{1}{2}$ then the min is $Y=1-U$
2) if $U \le \frac{1}{2}$ then the min is $Y=U$

1 )

First we calculate the interval extremes:

* if $U=\frac{1}{2}$ then $Y=\frac{1}{2}$

* if $U=1$ then $Y=0$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(1-U \le y)=P(-U \le y-1)=P(U \ge -y+1)=1-P(U \le 1-y)=1-F_U(1-y)=1-1+y=y$

Given that $\frac{\partial F}{\partial y}=1$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
1, & y \in [0,\frac{1}{2}] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(0,\frac{1}{2})$ by definition.

2 )

First we calculate the interval extremes:

* if $U=0$ then $Y=0$

* if $U=\frac{1}{2}$ then $Y=\frac{1}{2}$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(U \le y)=F_U(y)=y$

Given that $\frac{\partial F}{\partial y}=1$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
1, & y \in [0,\frac{1}{2}] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(0,\frac{1}{2})$ by definition.

c ) We have to find which function $f(x)$ such that $f(U) \sim U(a,b)$

Let $Y \sim U(a,b)$ with CDF:
$$
f_Y(y) = 
\begin{cases}
0, & y<a \\
\frac{y-a}{b-a}, & y \in [a,b] \\
1, & y>b
\end{cases}
$$
Given that $p=\frac{y-a}{b-a}$ is a probability, we know that $p$ takes values between 0 and 1. $p$ can be seen as a Standard Uniform ($p=U$). distribution.

$$
U=\frac{y-a}{b-a} \Rightarrow
U \times (b-a)=y-a \Rightarrow
U \times (b-a)+a=y
$$
The function is that transform a Standard Uniform in a $U(a,b)$ is indeed $f(U)=U \times (b-a)+a$


e ) We have to prove that $Y=max(U,1-U) \sim U(\frac{1}{2},1)$

We distinguish two cases:

1) if $U \ge \frac{1}{2}$ then the max is $Y=U$
2) if $U \le \frac{1}{2}$ then the max is $Y=1-U$

1 )

First we calculate the interval extremes:

* if $U=1$ then $Y=1$

* if $U=\frac{1}{2}$ then $Y=\frac{1}{2}$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(U \le y)=F_U(y)=y$

Given that $\frac{\partial F}{\partial y}=1$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
1, & y \in [\frac{1}{2},1] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(\frac{1}{2},1)$ by definition.

2 )

First we calculate the interval extremes:

* if $U=0$ then $Y=1$

* if $U=\frac{1}{2}$ then $Y=\frac{1}{2}$

We calculate the CDF:

$F_Y(y)=P(Y \le y)=P(1-U \le y)=P(-U \le y-1)=P(U \ge -y+1)=1-P(U \le 1-y)=1-F_U(1-y)=1-1+y=y$

Given that $\frac{\partial F}{\partial y}=1$ we derive the PDF:
$$
f_Y(y) = 
\begin{cases}
1, & y \in [\frac{1}{2},1] \\
0, & \text{otherwise}
\end{cases}
$$
which in turn is a $U(\frac{1}{2},1)$ by definition.














