---
title: "CTMC"
author: "Zuliani Riccardo"
date: "30/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("expm")
```

Generator Matrix
```{r}
dim <- 3
#G <- matrix(c(-1/3, 1/6, 1/6, 1/8, -1/6, 1/24, 1/48, 1/16, -1/12),ncol=dim, byrow=T)
G <- matrix(c(-4, 4, 0, 1, -7, 6, 6, 2, -8),ncol=dim, byrow=T)
G # Generator Matrix
```


Calculate the (conditional) transition probability matrix $\tilde{P_t}$
```{r}
P_tilde <- -G / diag(G)
diag(P_tilde) <- 0
P_tilde
```


Find the stationary distribution by solving the system $A \pi = b$:
```{r}
A <- G
A[,dim] <- rep(1,dim)
A <- t(A)

#Define the N-th canonical vector b and solve the linear system
b <- c(rep(0,dim-1),1)  # N-th canonical vector

p <- solve(A, b)
p
```


Conditional transition probability of discrete time chain $Z$ jumps
```{r}
t <- 2
states <- c(0,0,0)
initial_state <- 3
states[initial_state] <- 1
P_t = states %*% (P_tilde %^% t)
P_t
```

Transition probability of time t for the continuous time chain $P_t$
```{r}
t <- 1
expm(t * G)
```


```{r}
set.seed(9878) # Fix random number generator (for reproducibility)
T <- 10
n <- 0 # Counter for total number of jumps
t <- 0 # Current time
times <- 0 # Vector of jump times
x_t <- 1 # Current state: initializing at X(0)=1
x <- x_t # Vector of visited states
t_x1 <- 0

# Simulate the first holding time:
t <- rexp(1, -G[x_t, x_t])

t_x1 <- t_x1 + t

# Simulate sequentially until sopping rule:
while (t <= T){
  n <- n+1
  times <- c(times,t)
  x_t <- sample(1:dim, 1, prob = P_tilde[x_t,]) # I'm, in x_t state and I sample one of the other in order to take the transition probability

  x <- c(x, x_t)
  sim <- rexp(1, -G[x_t, x_t])
  if(x_t == 1){
    t_x1 <- t_x1 + sim
  }
  t <- t + sim
}

# The last jump (after time T) was never added, but we need to add the final time (T=10) and corresponding process value, to complete the plot
times <- c(times,T)
x <- c(x,x[n+1])

# Plot the path:
plot(times, x, type="s",col="blue", yaxt="n")
axis(side=2, at=1:dim)
t_x1 # total time spent in state 1 during the simulation
```

